### PR TITLE
Electron 25.3.2

### PR DESCRIPTION
**Pull request by mdouchement**
_Note that I'm not a JS expert._

### CODE REVIEW

**Comment by KevinRoebert** [comment]
LGTM

**Comment by fslori** [comment]
Great, thanks so much! :tada: :clap: 

Some notes I'd like to add:

- in order to allow a user community to interact (questions, bugs etc), you'll need to activate the 'issues' tab in GitHub (I would have used it for next bullets)
- the 'LibreRambox' name doesn't yet appear everywhere, sometimes it's still 'Rambox'. Should this be changed? Examples:
  - in the menus: File > Quit Rambox; Help > About Rambox
  - window title of the 'About Rambox' dialog
  - application name and main window title
- version 0.8.0 used the default system browser to open links; version 0.9.0 seems to open them in a Rambox window. That may be more isolated and secure, but on many occasions (at least for me) it's unwanted/unneeded and the link needs to be copy/pasted to the default browser e.g. in order to add a URL to the bookmarks. Is there some way to control this, or should this rather be changed in LibreRambox?

**Comment by mdouchement** [comment]
> version 0.8.0 used the default system browser to open links; version 0.9.0 seems to open them in a Rambox window. That may be more isolated and secure, but on many occasions (at least for me) it's unwanted/unneeded and the link needs to be copy/pasted to the default browser e.g. in order to add a URL to the bookmarks. Is there some way to control this, or should this rather be changed in LibreRambox?

Currently right click opens a menu where the link can be copied.

I was thinking about adding a popup, when clicking on a link, which offer the following choices:
- Open in Rambox's popup
- Open in Default OS Web Browser
- Copy Link

That's what `hamsket` and `tBox` do if I remember correctly.
But in the other hand, I prefer the simplest feature in order to make this project easily maintainable. The more complex a project is, the more difficult it is to maintain it up-to-date (time cost, dependencies conflicts/breaking changes, etc.) which can lead the project to be unmaintained.

**Comment by KevinRoebert** [comment]
@mdouchement Can you add a checkbox in the settings, which lets you choose whether to open links in Electron or OS Browser by default?

**Comment by fslori** [comment]
If possible (got it @mdouchement), I'd be happy (potentially many others too) with any approach that avoids the hassle of manually switching and pasting into a new browser tab. A general setting, right-click choice, ...

According to documentation of current official Rambox, they offer this as a setting at the level of each mail/messaging application. (see title 'Link handling' in https://support.rambox.app/support/solutions/articles/42000027661-how-to-create-and-configure-apps-). Adding this just as an extra idea, not necessarily as a reference.

**Pull request merged**
