### PR TITLE
Use Github actions to build and release Rambox in this repository

### PR DESCRIPTION
**Pull request by mdouchement**
- Update ProtonMail URL
- Everything is built by the workflow in this repository based on the work from `rambox-build` repository
  - Sencha
  - Electron builds
  - Releases

After this PR, I have this branch https://github.com/mdouchement/community-edition/tree/fix-vulns-2 which updates Rambox to Electron 24 (latest) which fix several CVEs.

### CODE REVIEW

**Comment by fslori** [comment]
You make my day @mdouchement, offering builds (https://github.com/mdouchement/community-edition/releases) with a recent Electron version in your fix-vulns branch! Through the jungle of Rambox forks, the LibreRambox organisation & fork already seemed a promising and ambitious step forward (with an inspiring name), given the stalled development of Rambox CE in 2020 and little maintenance of its fork Hamsket.

I'm glad I discovered this PR which I believe is indeed a very interesting one, using GH Actions.

Please consider @KevinRoebert!

**Comment by KevinRoebert** [comment]
LGTM

**Comment by KevinRoebert** [comment]
> After this PR, I have this branch https://github.com/mdouchement/community-edition/tree/fix-vulns-2 which updates Rambox to Electron 24 (latest) which fix several CVEs.

@mdouchement Are you still interested in creating the second PR?

**Comment by mdouchement** [comment]
Thank you for the merging, I'll create the next PR soon.

**Pull request merged**
